version: "3.1"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: reladb
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
