version: "3.1"

services:
  db:
    image: postgres:15.6
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: reladb
    # set user id for the docker container
    ports:
      - "5432:5432"
    user: "1000:1000"
    volumes:
      - ./db:/var/lib/postgresql/data
